<?php

namespace Admin\Controller;

use App\Controller\AppController as BaseController;
use Cake\Core\Configure;
use Cake\Event\Event;

/**
 * @property bool|object Menus
 * @property bool layout
 */
class AppController extends BaseController
{
    public $imageFields = [];

    public $filterEquals = ['status', 'group'];

    public function initialize()
    {
        parent::initialize();
    }

    public function index()
    {
        $searchFields = $this->request->query('S');
        $conditions = $searchFillFormData = [];
        if ($searchFields) {
            $equalFields = $this->filterEquals;
            foreach ($searchFields as $field => $value) {
                if ($value == null) {
                    continue;
                }
                $searchFillFormData['S['.$field.']'] = $value;
                if (in_array($field, $equalFields)) {
                    $conditions[$field] = $value;
                    continue;
                }
                $conditions[$field.' LIKE'] = '%'.$value.'%';
            }
        }
        $this->paginate['conditions'] = $conditions;
        $this->request->data = $searchFillFormData;
    }

    /**
     * @param Event $event
     */
    public function beforeRender(Event $event)
    {
        //$this->set('imageFields', $this->imageFields);
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }
}
