<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\I18n\Date;
use Cake\I18n\Time;

/**
 * InsuranceMst Controller
 *
 * @property \Admin\Model\Table\InsuranceMstTable $InsuranceMst
 */
class InsuranceMstController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public $deputy_mst_cate;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Admin.DeputytypeMst');
        $list = $this->DeputytypeMst->find('all')->toArray();
        $cate = $this->DeputytypeMst->buildTree($this->DeputytypeMst->generateCategories($list), 0, 'code');
        $this->set(compact('cate'));
    }

    public function index()
    {
        $insuranceMst = $this->paginate($this->InsuranceMst);

        $this->set(compact('insuranceMst'));
        $this->set('_serialize', ['insuranceMst']);
    }

    /**
     * View method
     *
     * @param string|null $id Insurance Mst id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $insuranceMst = $this->InsuranceMst->get($id, [
            'contain' => []
        ]);

        $this->set('insuranceMst', $insuranceMst);
        $this->set('_serialize', ['insuranceMst']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $insuranceMst = $this->InsuranceMst->newEntity();

        if ($this->request->is('post')) {

            $insuranceMst = $this->InsuranceMst->patchEntity($insuranceMst, $this->request->data);

            $insuranceMst->created_time = new Date($this->request->data['created_time']);
            $insuranceMst->update_time = new Date($this->request->data['update_time']);
            if ($this->InsuranceMst->save($insuranceMst)) {
                $this->Flash->success(__('The insurance mst has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The insurance mst could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('insuranceMst'));
        $this->set('_serialize', ['insuranceMst']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Insurance Mst id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $insuranceMst = $this->InsuranceMst->get($id, [
            'contain' => []
        ]);

        $insuranceMst->created_time = $insuranceMst->created_time->i18nFormat('yyyy-MM-dd');
        $insuranceMst->update_time = $insuranceMst->update_time->i18nFormat('yyyy-MM-dd');

        if ($this->request->is(['patch', 'post', 'put'])) {
            $insuranceMst = $this->InsuranceMst->patchEntity($insuranceMst, $this->request->data);

            $insuranceMst->created_time = date('Y-m-d', (time()));
            $insuranceMst->update_time = date('Y-m-d', (time()));
            if ($this->InsuranceMst->save($insuranceMst)) {
                $this->Flash->success(__('The insurance mst has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The insurance mst could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('insuranceMst'));
        $this->set('_serialize', ['insuranceMst']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Insurance Mst id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $insuranceMst = $this->InsuranceMst->get($id);
        if ($this->InsuranceMst->delete($insuranceMst)) {
            $this->Flash->success(__('The insurance mst has been deleted.'));
        } else {
            $this->Flash->error(__('The insurance mst could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}
