<?php
namespace Admin\Controller;

use Admin\Controller\AppController;
use Cake\I18n\Date;
use Cake\Utility\Security;
use Cake\Validation\Validator;
use Cake\I18n\Time;

/**
 * Users Controller
 *
 * @property bool layout
 * @property bool|object CurUser
 */
class UsersController extends AppController
{
    /**
     * Index method
     *
     * @return void
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Admin.AgentMember');
        $this->loadModel('Admin.AgentMst');
    }

    public function index()
    {
        parent::index();
        $users = $this->paginate('Users');
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }

    public function agentMembersList()
    {
        parent::index();
        $users = $this->paginate($this->Users->find('all', ['conditions' => ['group' => GROUP_AGENT]]));
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
        $this->set('user', $user);
        $this->set('_serialize', ['user']);
    }

    /**
     * Add method
     *
     * @param null $id
     * @return \Cake\Network\Response|void
     */
    public function form($id = null)
    {
        $user = $this->Users->newEntity()->accessible('email', true)->accessible('group', true)->accessible('status', true);

        if($id) 
        { // if edit method
            $user = $this->Users->get($id)->accessible('group', true)->accessible('status', true);
        }
        
        if ($this->request->is(['patch', 'post', 'put'])) 
        {               
            $user = $this->Core->patchEntity($user, $this->request->data);

            if ($this->Users->save($user))
            {                                
                $this->Flash->success(__('The user has been saved'), ['plugin' => 'Admin']);
                return $this->redirect(['action' => 'index']);
            } 
            else 
                {
                $this->Flash->error(__('The user could not be saved'), ['plugin' => 'Admin']);
            }
        }

        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }

    public function agentForm($id = null)
    {
        $user = $this->Users->newEntity()->accessible('email', true)->accessible('group', true)->accessible('status', true);

        if($id)
        { // if edit method
            $user = $this->Users->get($id)->accessible('group', true)->accessible('status', true);
        }

        if ($this->request->is(['patch', 'post', 'put']))
        {
            $user = $this->Core->patchEntity($user, $this->request->data);

            if ($this->Users->save($user))
            {
                $this->Flash->success(__('The user has been saved'), ['plugin' => 'Admin']);
                return $this->redirect(['action' => 'agentMembersList']);
            }
            else
            {
                $this->Flash->error(__('The user could not be saved'), ['plugin' => 'Admin']);
            }
        }

        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }

    public function agentMembersForm($id = null)
    {
        $agent_member = $this->AgentMember->newEntity();
        $agent_mst = $this->AgentMst->getCodeValue();

        if($id)
        { // if edit method
            $agent_member_info = $this->AgentMember->find('all')->where(['agent_member_id' => $id])->first();
            if($agent_member_info) {

                $agent_member = $agent_member_info;
                $agent_member->birthday = $agent_member->birthday->i18nFormat('yyyy-MM-dd');
                $agent_member->created_time = $agent_member->created_time->i18nFormat('yyyy-MM-dd');
                $agent_member->update_time = $agent_member->update_time->i18nFormat('yyyy-MM-dd');
            }else{
                $agent_member->birthday = date('Y-m-d', (time()));
                $agent_member->created_time = date('Y-m-d', (time()));
                $agent_member->update_time = date('Y-m-d', (time()));
            }
        }

        if ($this->request->is(['patch', 'post', 'put']))
        {

            $agent_member = $this->Core->patchEntity($agent_member, $this->request->data);

            $agent_member->agent_member_id = $id;
            $agent_member->birthday = new Date($this->request->data['birthday']);
            $agent_member->created_time = new Date($this->request['created_time']);
            $agent_member->update_time = new Date($this->request->data['update_time']);

            if ($this->AgentMember->save($agent_member))
            {
                $this->Flash->success(__('The user has been saved'), ['plugin' => 'Admin']);
                return $this->redirect(['action' => 'agentMembersList']);
            }
            else
            {
                $this->Flash->error(__('The user could not be saved'), ['plugin' => 'Admin']);
            }
        }

        $this->set(compact('agent_member', 'agent_mst'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return void Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('The user has been deleted'), ['plugin' => 'Admin']);
        } else {
            $this->Flash->error(__('The user could not be deleted'), ['plugin' => 'Admin']);
        }
        return $this->redirect(['action' => 'index']);
    }
    public function deleteAgentMember($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('The user has been deleted'), ['plugin' => 'Admin']);
        } else {
            $this->Flash->error(__('The user could not be deleted'), ['plugin' => 'Admin']);
        }
        return $this->redirect(['action' => 'agentMembersList']);
    }

    public function logout()
    {
        $this->request->session()->destroy();
        $this->redirect(['plugin' => null, 'controller'=>'users','action'=>'login']);
    }

    /**
     * profile of the current user login
     *
     * @return \Cake\Network\Response|void
     */
    public function profile()
    {
        $user = $this->Users->get($this->CurUser->id);

        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Core->patchEntity($user, $this->request->data);
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved'), ['plugin' => 'Admin']);
                return $this->redirect(['action' => 'profile']);
            } else {
                $this->Flash->error(__('The user could not be saved'), ['plugin' => 'Admin']);
            }
        }
        
        $this->set(compact('user'));
    }

    /**
     * Update the password
     *
     * @return \Cake\Network\Response|void
     */
    public function change_password()
    {
        $user = $this->Users->get($this->CurUser->id);

        if($this->request->is(['patch', 'post', 'put']))
        {
            $oldPass = $this->request->data['old_password'];
            $oldPassHash = Security::hash($oldPass, 'sha1', true);

            if($oldPass && $oldPassHash != $user->password) 
            {
                $user->errors('old_password', [__('The current password incorrect')]);
                $this->Flash->error(__('The password could not be changed'), ['plugin' => 'Admin']);
            } 
            else 
            {
                $user->password = $this->request->data['new_password'];
                $user = $this->Users->patchEntity($user, $this->request->data);
                
                if ($this->Users->save($user)) 
                {
                    $this->Flash->success(__('The password has been changed'), ['plugin' => 'Admin']);
                    return $this->redirect(['action' => 'change_password']);
                } 
                else 
                {                    
                    $this->Flash->error(__('The password could not be changed'), ['plugin' => 'Admin']);
                }
            }
        }

        $this->set(compact('user'));
    }

    public function set_theme()
    {
        $this->viewBuilder()->layout(false);
        $this->autoRender = false;

        $theme = $this->request->query['theme'];
        $user = $this->Users->get($this->CurUser->id);
        $user->smart_admin_themes = $theme;
        $status = true;

        if (!$this->Users->save($user)) {
            $status = false;
        } else {
            $this->CurUser->smart_admin_themes = $theme;
            $this->request->session()->write('Core.Users', $user);
        }

        echo json_encode(['status' => $status]);
    }
}
