<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * InsurancecompanyMst Controller
 *
 * @property \App\Model\Table\InsurancecompanyMstTable $InsurancecompanyMst
 */
class InsurancecompanyMstController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->layout('admin');

    }

    public function index()
    {
        $insurancecompanyMst = $this->paginate($this->InsurancecompanyMst);

        $this->set(compact('insurancecompanyMst'));
        $this->set('_serialize', ['insurancecompanyMst']);
    }

    /**
     * View method
     *
     * @param string|null $id Insurancecompany Mst id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $insurancecompanyMst = $this->InsurancecompanyMst->get($id, [
            'contain' => []
        ]);

        $this->set('insurancecompanyMst', $insurancecompanyMst);
        $this->set('_serialize', ['insurancecompanyMst']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $insurancecompanyMst = $this->InsurancecompanyMst->newEntity();
        if ($this->request->is('post')) {
            $insurancecompanyMst = $this->InsurancecompanyMst->patchEntity($insurancecompanyMst, $this->request->data);
            if ($this->InsurancecompanyMst->save($insurancecompanyMst)) {
                $this->Flash->success(__('The insurancecompany mst has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The insurancecompany mst could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('insurancecompanyMst'));
        $this->set('_serialize', ['insurancecompanyMst']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Insurancecompany Mst id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $insurancecompanyMst = $this->InsurancecompanyMst->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $insurancecompanyMst = $this->InsurancecompanyMst->patchEntity($insurancecompanyMst, $this->request->data);
            if ($this->InsurancecompanyMst->save($insurancecompanyMst)) {
                $this->Flash->success(__('The insurancecompany mst has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The insurancecompany mst could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('insurancecompanyMst'));
        $this->set('_serialize', ['insurancecompanyMst']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Insurancecompany Mst id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $insurancecompanyMst = $this->InsurancecompanyMst->get($id);
        if ($this->InsurancecompanyMst->delete($insurancecompanyMst)) {
            $this->Flash->success(__('The insurancecompany mst has been deleted.'));
        } else {
            $this->Flash->error(__('The insurancecompany mst could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}
